name: Release Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  appimage-x86_64-build:
    runs-on: [ubuntu-latest, x64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg desktop-file-utils fuse patchelf wget

      - name: Run AppImage Build Script
        run: scripts/build_appimage.sh
        shell: bash

      - name: Upload AppImage Executable
        uses: actions/upload-artifact@v4
        with:
          name: OnTheSpot-x86_64.AppImage
          path: dist/OnTheSpot-x86_64.AppImage

      - name: Upload to Release (AppImage)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/OnTheSpot-x86_64.AppImage
          asset_name: OnTheSpot-x86_64.AppImage
          asset_content_type: application/octet-stream
